version: "3.3"

services:
  tor:
    container_name: tor
    build:
      context: tor
    image: tor_img
    port:
      - "9050:9050"
      - "9051:9051"
    expose:
      - "9050"
      - "9051"

  btc_sig_node:
    container_name: btc_sig_node
    build:
      context: bitcoind_signet_node
    image: bitcoind_signet_node
    volumes:
      - shared_vol_btc:/bitcoind
    port:
      - "38333:38333"
      - "38332:38332"
    expose:
      - "38333"
      - "38332"

  nginx:
    container_name: nginx
    build:
      context: nginx
    image: nginx_img
    port:
    expose:
      - "60602"

  c-lightning:
    container_name: c-lightning
    build:
      context: c-lightning
    image: core_lightning
    volumes:
      - shared_vol_ln:/lightningd
    port:
      - "39735:39735"
      - "3092:3092"
    expose:
      - "39735"
      - "3092"

  lnbits:
    container_name: lnbits
    build:
      context: lnbits
    image: lnbits_img
    volumes:
      - shared_vol_ln:/lightningd
    port:
      - "7000:7000"
    expose:
      - "7000"

  rtl:
    container_name: rtl
    build:
      context: rtl
    image: rtl_img
    volumes:
      - shared_vol_ln:/lightningd
    port:
      - "3000:3000"
    expose:
      - "3000"

volumes:
  shared_vol_btc:
  shared_vol_ln:
